server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hdupr2
    username: root
    password: 2123092
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #实体类别名包路径
  type-aliases-package: cn.hdu.newyork.domain
configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl